name: build_and_publish_binaries

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build linux amd64
        run: make release
      - name: Build linux arm6
        run: make release-pi
      - name: Build linux arm5
        run: make release-pi1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux/amd64/mansioneye
            build/linux/arm6/mansioneye-arm6
            build/linux/arm5/mansioneye-arm5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
